### ISSUE TITLE
https://github.com/PhilippeSigaud/Pegged/wiki/Parsing-Levels : is it still supported?

### ISSUE THREAD

**Issue by timotheecour** [PhilippeSigaud/Pegged#148]
Eg, I couldn't find noDecimation in the code.

**Comment by PhilippeSigaud** [comment]
No, it's not supported any more: at some time I rewrote the engine and did
not put this functionality back, because it causes a huge inflation in the
generated code size and that reached the limits of the CTFE engine at the
time.

Maybe I should put some indication in the Wiki about it.
