### ISSUE TITLE
docs will not generate: alias unmatched?

### ISSUE THREAD

**Issue by cyisfor** [PhilippeSigaud/Pegged#158]
pegged/peg.d(2680): Error: alias pegged.peg.backquote unmatched --- in DDoc comment

backquote has special meaning in ddoc, and it's _supposed_ to treat an unmatched backtick as a literal backtick, but for some reason it errors out instead, despite the docs saying differently. It appears to be treating the text " (backquote)" as if it were code. Anyway, the API documentation generates if you substitute the $(BACKTICK) macro for ` in that line's comment.

DMD64 D Compiler v2.067
Copyright (c) 1999-2014 by Digital Mars written by Walter Bright

**Comment by PhilippeSigaud** [comment]
OK, I changed ligne 2680 to use $(BACKTICK) instead of `.

I don't have an easy access to a D compiler right now. Could you please see
if that works with your DMD version?

I yes, I'll push the Pegged version to 0.2.2, so that dub catches it.

**Comment by PhilippeSigaud** [comment]
Thats commit da9306f627ff060029dd9e7a5e10ebd791d34bc2, btw.

**Comment by PhilippeSigaud** [comment]
OK, I downloaded and installed DMD 2.067.1 (wow, much faster than a year ago!).

```shell
rdmd -unitest -D pegged/dev/test.d
```

compiles without trouble.

**Comment by cyisfor** [comment]
Just wanted to say thanks!

**Comment by PhilippeSigaud** [comment]
You're welcome!
