### ISSUE TITLE
Rules parametrized by input

### ISSUE THREAD

**Issue by child** [PhilippeSigaud/Pegged#160]
I need to parse a syntax were one rule consists of a number followed by this number of chars. Generally it would like something like:

```
Literal <- "{" Number "}" Char+
```

but instead of "+" at the end I would need to use the number that was parsed earlier in the rule.

Is it possible to implement this using semantic actions or something else?

**Comment by PhilippeSigaud** [comment]
Thank you for trying Pegged!

Yes, what you want is possible with semantic actions. Here is a proof of
principle:

```d
import pegged.grammar;

PT validate(PT)(PT pt) {
  // pt.children[0]: '{'
  // pt.children[1]: the Number parse tree.
  //                 The number itself is the first (and only) match
  // pt.children[2]: '}'
  // pt.children[3]: The CharN parse tree
  //                 We want the length of the forst (and only) match

  import std.stdio;
  import std.conv: to;
  size_t numRead = pt.children[1].matches[0].to!(size_t);
  size_t numOfChars = pt.children[3].matches[0].length;
  writeln("Number read between '{}': ", numRead);
  writeln("Num of chars read after '}': ", numOfChars);

  if (numRead.to!(size_t) == numOfChars ) {
    writeln("Validation OK.");
  } else {
    writeln("Bad number of chars.");
    pt.successful = false; // To invalidate the parsing.
  }

  return pt;
}

mixin(grammar(`
Test:
    Literal <- ('{' Number '}' CharN) {validate}
    Number <~ [0-9]+
    CharN <~ .*
`));


void main() {
  writeln(Test("{12}aaaaaaaaaaaa")); // OK
  writeln(Test("{12}aaaaaaaaaaa")); // NOK (12 != 11 times 'a')
  writeln(Test("{12}aaaaaaaaaaaaa")); // NOK (12 != 13 times 'a')
  writeln(Test("{12}qwzerty01234")); // OK
}
```

The idea with semantic action is that you have access to the current parse
tree, and can modify it if you wish. In this case, we test for your
assumption and make the parse a failure (`pt.successful = false;`) if it's
not met. We could also log the number elsewhere, and so on.

Note that it's not complete nor perfect: I did not restrict the CharN rule
in any way (it'll happily consume the rest of the input). Also, in some
cases (`{0}` for example, or even `{12}`) it'll fail because CharN has no
match in this case, but that's easily tested for.

Tell me if I understood you correctly and if you need any further
explanation concerning this.

**Comment by child** [comment]
Thank you Philippe

Your explanation was quite thorough, but I'm afraid I did not describe my problem well enough. The issue is not with validation, but with fact there is more input following CharN and I need my Literal rule to not consume it.

A limited example:

```
Test:
  ParLiteral <- "(" Literal ")"
  // The rest as in your example

...

void main () {
writeln(Test("({12}aaaaaaaaaaaa)")) // NOK - CharN rule consumes trailing ")"
}
```

In my case CharN can contain any character, so I can't exclude ")" from it.

**Comment by PhilippeSigaud** [comment]
OK. Then we can use the semantic action to regurgitate some chars if we
consumed too much. I never tired that before, but that seems to work :)

```D
import std.stdio;
import pegged.grammar;

PT validate(PT)(PT pt) {
  import std.conv: to;
  long numRead = pt.children[1].matches[0].to!(long);
  long numOfChars = pt.children[3].matches[0].length;
  long overshoot = numOfChars - numRead;
  if (overshoot >= 0 ) { // CharN gobbled more than it should
    pt.end -= overshoot; // We go back some chars
    pt.matches[3] = pt.matches[3][0 .. $ - overshoot];
    pt.children[3].matches[0] = pt.children[3].matches[0][0 .. $ -
overshoot];
  } else { // Not enough char gobbled: failure
    pt.successful = false; // To invalidate the parsing.
  }

  return pt;
}

mixin(grammar(`
Test:
    ParLiteral <- '(' Literal ')'
    Literal <- ('{' Number '}' CharN) {validate}
    Number <~ [0-9]+
    CharN <~ .*
`));


void main() {
  writeln(Test("({12}aaaaaaaaaaaa)")); // Parses OK, ')' left to ParLiteral
  writeln(Test("({12}aaaaaaa)")); // Fails: too few a's
  writeln(Test("({12}aaaaaaaaaaa)")); // Fails: CharN consumes 11 a's + the
')', leaving nothing for ParLiteral end paren
  writeln(Test("({11}aaaaaaaaaaaa)")); // Fails: CharN consumes only 11
a's, and ParLit does not find a ')' but an 'a'.
  writeln(Test("({1}a)")); // Parses OK
}
```

**Comment by child** [comment]
This works perfectly, thank you!
