### ISSUE TITLE
introspection.d infinite recursion during CTFE.

### ISSUE THREAD

**Issue by veelo** [PhilippeSigaud/Pegged#166]
Found another infinite recursion in introspection.d, but one that only occurs during CTFE. Not sure what is going on, maybe a bug in D?

```D
unittest // Mutual left-recursion
{
    enum info = ruleInfo(`
      Left:
        L <- P
        P <- P / L
    `);
    assert(info["L"].leftRecursion == LeftRecursive.indirect);
    assert(info["P"].leftRecursion == LeftRecursive.direct);
}
```

Whet executed at runtime, by changing `enum` to `auto`, this test does complete.

**Comment by PhilippeSigaud** [comment]
IIRC (that was some years ago), I wrote the introspection code to be used
at runtime. The idea was to create a grammar that could be modified by the
user, even after being created (A plan to introduce lisp-like macros in D
that needed a runtime-configurable grammar to parse D modules before
invoking the compiler. But anyway...)


IIRC also, I abandonned it after getting to many bugs in associative arrays
at runtime. I decided to wait for them to become more stable.

That was quite long ago for me, I'm afraid I cannot help much there.

I think I should look for someone willing to become the new developer &
maintainer. I'm too far away from D and Pegged right now... I cannot help
anymore the people asking questions...

**Comment by veelo** [comment]
Thanks. I didn't expect you to have an answer ready to this one :-) I may be able to reduce this and ask on the forum.

I am not sure yet whether to use introspection.d or write something close to it from scratch. I need some form of introspection in grammar.d. Introspection.d does a little too much and a little too little, but I thought I might use it as a starting point. I can version() it out for __ctfe for now since left-recursion is runtime only currently, but eventually ctfe would be nice to support.

I'll see.

**Comment by veelo** [comment]
I know what the problem is. Actually, the recursion protection in my first PR (#163) is not quite sufficient, this unittest will infinitely recurse depending on the order in which rules are tested for left-recursion. Since rules are traversed using foreach over an associative array (https://github.com/PhilippeSigaud/Pegged/blob/master/pegged/dev/introspection.d#L347) the order is undetermined. Confusingly, the order at compile time is different from the order at run time.

A pity that this is hard to debug in absence of __ctfteWrite (https://github.com/D-Programming-Language/dmd/pull/692).

**Comment by PhilippeSigaud** [comment]
I think that comes from the way AA are built and updated. The mechanism is
probably different for CT and RT.

Isn't there a property (or a function) like `.byKeys()` for AAs? Maybe it
could provide the same iteration order?

Or else, we could ditch AA for this and use a simple array of Name/Property
pairs... Linear scan but hey, since we traverse the entire AA anyway...

**Comment by veelo** [comment]
Steven Schveighoffer suggested rbtree for consistent order between CT and RT (http://forum.dlang.org/post/n32v58$1dql$1@digitalmars.com).

[Rambling on from here on, ignore if you have better things to do]
But the real problem is that the recursion guard `maybeLeftRecursive` that I introduced uses `target` as the index. That works if the second rule `P <- P / L` is scanned first, where `P` is the target. But if the first rule is scanned first, `L` is the target, and when it recurses to test `P`,  `maybeLeftRecursive` keeps looking up `L` so that won't work to prevent infinite recursion on `P`.

As a test I've considered using `matches[0]` to index `maybeLeftRecursive`, but then the unittest for hidden left-recursion fails.

This particular grammar is a bit special as the second rule is both directly as well as indirectly left-recursive.

I have considered a staged approach: first scan for direct left-recursion, then scan the remaining rules for indirect left-recursion, so the latter won't get caught in a different cycle. But that won't be generic enough: if two cycles of indirect left-recursion pass through the same node (like "8") there will still be problems.

I'll have to think about this more. Ordinary recursion detection doesn't seem to have this problem, maybe I should build on that.

**Comment by PhilippeSigaud** [comment]
What about reimplementing a small, specific, AA with an array+hashing
function and linked-lists (or dyn. arrays) for buckets? In this particular
case, we do not need a generic array: the type of keys and values is
already known...
A simple hashing function would deliver the same value at CT or R, hence
the resulting AA would be the same. As for the iteration scheme, well,
that's up to you by offering empty/front/popFront methods that act the same
with CTFE or runtime execution.

**Comment by veelo** [comment]
The difference between CT and RT is not really the issue here, it is the algorithm that is flawed. It should work regardless of the order of the rules.
