### ISSUE TITLE
Is CI section in README.md outdated?

### ISSUE THREAD

**Issue by veelo** [PhilippeSigaud/Pegged#179]
http://ci.lycus.org seems to be down.

**Comment by PhilippeSigaud** [comment]
On Sun, Jan 31, 2016 at 10:17 PM, Bastiaan Veelo <notifications@github.com>
wrote:

> http://cilycusorg seems to be down
>

It was added by another contributor. I personally never used it. If it's
dead then let's delete this part.

**Comment by veelo** [comment]
Fixed in 6d767bb134c317956b1c2b787bfbac280077818d.
