### ISSUE TITLE
v0.3 is an invalid SEMVER version, breaking dub.

### ISSUE THREAD

**Issue by SuperDoxin** [PhilippeSigaud/Pegged#180]
it's currently impossible to use release v0.3 from dub as it is an invalid version. if you could re-do the release with v0.3.0 as tag it'd probably fix it.

**Comment by PhilippeSigaud** [comment]
Drat. I'll push a v0.3.0 tag.

**Comment by PhilippeSigaud** [comment]
Ok, I just pushed a `v0.3.0` tag. That should be caught by the dub servers tonight. Sorry for the mess.

**Comment by SuperDoxin** [comment]
awesome, thanks!
