### ISSUE TITLE
Using custom action functions results in error with asModule

### ISSUE THREAD

**Issue by Temtaime** [PhilippeSigaud/Pegged#191]
Because there's currently no way to tell to generated module import some file with those functions.

**Comment by veelo** [comment]
How about
```d
	asModule!()("myparser", "myparser", MyGrammar, "import myActions;\n");
```

**Comment by Temtaime** [comment]
I see :(
So i think there's should be a reference from tutorial to this optional argument

**Comment by veelo** [comment]
You want to have a go? It's wiki :-)

**Comment by Temtaime** [comment]
Thanks, fixed !

**Comment by veelo** [comment]
Thank you.
