### ISSUE TITLE
How to parse newlines correctly?

### ISSUE THREAD

**Issue by skocznymroczny** [PhilippeSigaud/Pegged#201]
I'm playing around with the idea of writing an interpreter for a toy programming language, but I can't get over a simple issue with parsing using pegged library.

My input file looks like this:

```
\n
\n
a <- xxx\n
\n
\n
b <- yyy\n
```

(I replaced newlines with \n here in this example to make the newlines visible).

I am using this grammar to parse it:

```
mixin(grammar(`
SampleLang:
	File					<- Line+
	Line					<- EmptyLine / Statement
	Statement				<- Declaration endOfLine
	EmptyLine				<- endOfLine
	Declaration             < identifier "<-" identifier
`));
```

I expect the output to be something like:
file -> emptyline -> emptyline -> statement -> declaration -> emptyline -> emptyline -> statement -> declaration

meanwhile all I get is:
```
SampleLang [0, 4]["\n", "\n"]
 +-SampleLang.File [0, 4]["\n", "\n"]
    +-SampleLang.Line [0, 2]["\n"]
    |  +-SampleLang.EmptyLine [0, 2]["\n"]
    +-SampleLang.Line [2, 4]["\n"]
       +-SampleLang.EmptyLine [2, 4]["\n"]
```

What's wrong with this grammar? It looks OK in my opinion.

**Comment by veelo** [comment]
Try changing `File` to
```
    File                    <- Line+ endOfIndput
```

**Comment by skocznymroczny** [comment]
OK, I guess I solved my issue.

 Declaration             < identifier "<-" identifier

this, because it's using < was stripping my whitespace, including any empty lines coming after it. After switching it to <-, it wouldn't strip whitespace anymore, but because of that it wouldn't match with a <- xxx because of the spaces around <-. After switching to:

Declaration             <- identifier " " "<-" " " identifier

it works as expected (I guess identifier Spacing "<-" Spacing identifier) would work nicely too.
