### ISSUE TITLE
Wrong info in tutorial

### ISSUE THREAD

**Issue by Domain** [PhilippeSigaud/Pegged#202]
In the section "Extended PEG Syntax":

> In particular, **char and string literals terminals are always dropped** unless Pegged is told otherwise (see next extension).

 That's not true.

**Comment by PhilippeSigaud** [comment]
Maybe what that's badly written but look:

```d
import pegged.grammar;

mixin(grammar(`
Test:
    A <- B 'c' D
    B <- 'b'
    D <- 'd'
`));


void main() {
  writeln(Test("bcd"));
}
```

The 'c' literal is not present in the parse tree, only the B and D rules
remain:

```
Test [0, 3]["b", "c", "d"]
 +-Test.A [0, 3]["b", "c", "d"]
    +-Test.B [0, 1]["b"]
    +-Test.D [2, 3]["d"]
```

**Comment by Domain** [comment]
OK, I see. Drop in node, but present in matches.

**Comment by PhilippeSigaud** [comment]
There is also the difference between discarding and dropping a node.

See : https://github.com/PhilippeSigaud/Pegged/wiki/Extended-PEG-Syntax

Should I make the docs clearer?
