### ISSUE TITLE
Unit test fails

### ISSUE THREAD

**Issue by Stretto** [PhilippeSigaud/Pegged#211]
Running the unit test in DMD latest x86:

unittest // Null-matching left-recursion
{
    enum NullMatch = `
      Test:
        M <- S (";" S)* eoi
        S <- S '+' S / 'n' / eps
`;
    mixin(grammar(NullMatch)); // <-- fails here
    assert(Test("n+n;n;").matches == ["n", "+", "n", ";", "n", ";", ""]);
}

fails with

pegged\peg.d(1426): Error: variable pegged.peg.or!(and, literal, eps).ctfeGetNameOr.rule variables cannot be of type void
pegged\grammar.d-mixin-3060(3204): Error: template instance pegged.peg.or!(and, literal, eps) error instantiating
pegged\grammar.d-mixin-3060(3271):        instantiated from here: GenericTest!(ParseTree)

**Comment by veelo** [comment]
It works for me:
```
$ dmd -main -unittest pegged/peg.d pegged/grammar.d pegged/parser.d pegged/introspection.d pegged/dynamic/grammar.d pegged/dynamic/peg.d
$ dmd --version
DMD64 D Compiler v2.071.1
Copyright (c) 1999-2015 by Digital Mars written by Walter Bright
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004
$ git log
commit 429d4a855741f1b4896caf90bdafc6a29f937748
Merge: 6b99018 ff25688
Author: Philippe Sigaud <philippe.sigaud@gmail.com>
Date:   Wed May 18 07:31:24 2016 +0200

    Merge pull request #209 from ReneZwanenburg/master
    
    Fix DMD 2.071 import deprecations
```

Please provide more version/system information.

**Comment by Zardoz89** [comment]
I think that you should close this issue, as was happening with the master branch before releasing the v0.3.3. This now only generates noise on the issues list.

**Comment by veelo** [comment]
Agreed, thanks.
