### ISSUE TITLE
New release request for  #214

### ISSUE THREAD

**Issue by o3o** [PhilippeSigaud/Pegged#215]
Dear Philippe,
can you please publish a new version that fix #214?

Thank you

**Comment by PhilippeSigaud** [comment]
Done, I created v0.3.3. That should be caught by dub in 24 hours.

**Comment by o3o** [comment]
Thank you again

**Comment by BBasile** [comment]
Hi i need a tag too, otherwise i have to use ~master, which DUB doesn't like since it's not a semver string.
