### ISSUE TITLE
toHTML, add static options to render expanded trees

### ISSUE THREAD

**Issue by BBasile** [PhilippeSigaud/Pegged#228]
At least a feature to fully expand, but even better could be done, such as expand the nodes passed as template params:

```d
toHTML!Expanded.Yes(tree, "file.html");
toHTML!("NodeA", "NodeB")(tree, "file.html");
```

**Comment by veelo** [comment]
Thanks for this addition, @BBasile . Can you document it where toHTML is presented, on https://github.com/PhilippeSigaud/Pegged/wiki/Using-the-Parse-Tree and/or https://github.com/PhilippeSigaud/Pegged/wiki/Parse-Result? Thanks.

**Comment by BBasile** [comment]
Sure. But for the compatibility with the toLaTeX() example  i'm no competent.

**Comment by veelo** [comment]
Thanks, that is exactly what I meant. No need to worry about compatibility with `toLaTeX`, as these have (confusingly) nothing to do with each other. `toLaTeX` is the example of how input can be transcompiled into something different (Wiki -> LaTeX), _using_ the Pegged-generated parse tree. `toString` and `toHTML` are methods for just _writing out_ a parse tree. Maybe we should rename this example to prevent the confusion.
