### ISSUE TITLE
Is there a way to build grammars at runtime for purpose of making a Pegged GUI app ?

### ISSUE THREAD

**Issue by enjoysmath** [PhilippeSigaud/Pegged#232]
Coincidentally, I couldn't get asModule to work, it's as if the compiler is not finding its defintion.

Anyway, I wanted to make a C# GUI app like GOLD Parser Builder but much simpler that works with Pegged lib.  However, building the grammars takes 5 minutes (e.g. Cgrammar in examples).  So is there a way to do it at run-time and really fast?

It's okay if the output is more .d modules that have to be compiled.

Thanks.

**Comment by veelo** [comment]
You could generate a parser module at run-time by invoking rdmd as a separate process, I guess? Have a look at https://github.com/PhilippeSigaud/Pegged/blob/master/pegged/examples/extended_pascal/source/make.d.

**Comment by enjoysmath** [comment]
@veelo  link broken.

**Comment by veelo** [comment]
https://github.com/PhilippeSigaud/Pegged/blob/master/examples/extended_pascal/source/make.d
