### ISSUE TITLE
Case where toHTML doesn't display well the content of the captures

### ISSUE THREAD

**Issue by BBasile** [PhilippeSigaud/Pegged#239]
Run this

```d
import pegged.grammar, pegged.peg, pegged.tohtml;

enum rules =
`   SB:
    Everything <- SheBangLine? Remaining
    SheBangLine <- "#!" (!endOfLine .)* endOfLine
    Remaining <- (!eoi .)*
`;

enum sample1 =
`#!excluded
included line 2
included line 3
  #!included line 4
`;
enum sample2 =
`
#!included b/c not first line
included line 2
included line 3
  #!included line 4
`;

mixin(grammar(rules));

void main()
{
    const ParseTree s1 = SB(sample1);
    const ParseTree s2 = SB(sample2);
    toHTML(s1, "s1.html");
    toHTML(s2, "s2.html");
}
```

and look at [`s2.html`](https://jsfiddle.net/qsh7od3s/).
The page doesn't display the captures but they are well in the HTML code.

**Comment by veelo** [comment]
Confirmed. How would you propose to handle this case? We could insert &#x23ce; for every empty line at the beginning of the match. Have a look and change row 45 in [s2.html](https://jsfiddle.net/qsh7od3s/) with
````
     <details><summary>SB [0, 83] <code>&#x23ce;<span><pre>&#x23ce;
````
What do you think?

**Comment by BBasile** [comment]
Yes, this would avoid the confusion. However i'm not into HTML at all so i can't say if there's a better solution (i don't no what exactly the problem either).

**Comment by veelo** [comment]
OK. (The problem is that in an empty line there is nothing that the mouse pointer can hover over that would make the full match appear. So we need to show something that was not actually part of the match. A space would also work, but still be confusing.)

**Comment by BBasile** [comment]
Let's add the symbol _always_. It's a very particular case where Pegged is used to do what a scanner would usually do. toHTML was just used to test a rule and whatever is done to fix this here we're on the display, this will never break anything. I mean that if adding the symbol _always_ is ever proven to be a wrong decision, this still can be fixed without breaking anything...toHTML is meant to check the grammar after all.

**Comment by veelo** [comment]
I don't follow you. Surely, you wouldn't want the first line of the match in `s1.html` to be displayed as "&#x23ce;#!excluded"?

**Comment by BBasile** [comment]
Yeah, only "⏎" for empty lines.

**Comment by veelo** [comment]
O, right. I'm not in favor of that, as I think it will clutter the output and make it optically distinct from how you would view the input in an editor. And to be consistent, we'd need to display all line breaks and possibly white space also. Maybe someone would want that, but I think it would be best enabled as an option (to show all non-printable content everywhere).

**Comment by BBasile** [comment]
This case will be very rare. Let's start with your solution then.
