### ISSUE TITLE
Wiki page "Named captures" is out of date

### ISSUE THREAD

**Issue by BBasile** [PhilippeSigaud/Pegged#241]
see https://github.com/PhilippeSigaud/Pegged/wiki/Named-Captures.
The example doesn't compile, even with a quick fix to the grammar.

```d
module runnable;

import std.stdio;
import pegged.parser;
import pegged.grammar;
import pegged.peg;

mixin(grammar("
G:
Email <- Name '@' Domain
Name <- QualifiedIdentifier
Domain <- QualifiedIdentifier
QualifiedIdentifier <- Identifier ('.' Identifier)*
Identifier <- [a-z, A-Z]*
"));

void main(string[] args)
{
    enum p = G("john.doe@example.org");
    assert(p.namedCaptures["name"] == "john.doe");
    assert(p.namedCaptures["domain"] == "example.org");
}
```

> /tmp/temp_7F011F4DB5F0.d(21,13): Error: no property 'namedCaptures' for type 'ParseTree'
/tmp/temp_7F011F4DB5F0.d(22,13): Error: no property 'namedCaptures' for type 'ParseTree'

**Comment by BBasile** [comment]
I suppose that the API has changed since 2012 so you should delete the page ?
Nowadays we have `p.matches[]` but it's indexed by an integer.

**Comment by PhilippeSigaud** [comment]
Yes indeed, it's an old API that does not exist anymore (it existed for just a few weeks IIRC). I see the wiki page is already 'outside' the tutorial, I'll delete it. Good catch!

**Comment by PhilippeSigaud** [comment]
Hmm, that's strange. I deleted the page, but I still got it when I update the wiki pages from a clean install.

Could you try to do:

```bash
$ cd <pegged directory>
$ git submodule init
$ git submodule update
```
And see if the `Named-Captures.md` file is still there?

**Comment by BBasile** [comment]
looks ok, the link lead to an editor for a new page.

**Comment by KrzaQ** [comment]
So, to be clear, there is no such functionality at this time and I should use indexes instead?

**Comment by PhilippeSigaud** [comment]
Sorry, I didn't see your question. There is indeed no such functionality in Pegged.
