### ISSUE TITLE
Grammar Examples do not compile

### ISSUE THREAD

**Issue by FraMecca** [PhilippeSigaud/Pegged#266]
I think that some grammar exaples got out of date.

I suggest to put them into the tests so that for every test run you can check that they still compile and work as examples.

In particular, I am referring to https://github.com/PhilippeSigaud/Pegged/blob/master/pegged/examples/PEG.d

**Comment by Zardoz89** [comment]
Actually al grammar examples, except the C Grammar, at least compiles (dub build). The CI servers try to build every example, except the C grammar that need to be fixed. How ever, many examples need to be improved to test better.

**Comment by baryluk** [comment]
I can confirm. All grammar examples, except the C grammar , compile for me too, using LDC 1.12.0.

**Comment by veelo** [comment]
The C grammar has been fixed, some grammars are now more thoroughly tested.
