### ISSUE TITLE
dub generate visuald + pegged no longer works

### ISSUE THREAD

**Issue by enjoysmath** [PhilippeSigaud/Pegged#268]
mixin(grammar(typeCheckerGrammar));
![image](https://user-images.githubusercontent.com/1606391/70377440-5910fc80-18c9-11ea-947d-1345370d1056.png)

Gives static assert error on most basic grammar.
To recreate:

Install Visual Studio 2019 Community.  Install VisualD.  At command line:
dub init my_project
cd my_project
dub build
dub generate

**Comment by veelo** [comment]
You are not giving it a valid Pegged grammar. You need to start with the name of the grammar followed by a colon. For example: https://github.com/PhilippeSigaud/Pegged/wiki.

**Comment by veelo** [comment]
Please close if this solved your issue.
