### ISSUE TITLE
Update readme.md with CI badges

### ISSUE THREAD

**Issue by Zardoz89** [PhilippeSigaud/Pegged#281]
When Travis CI and AppVeyor are enabled for this repository, would be highly recomendable to add the CI status badges : 

[![Build Status](https://travis-ci.com/PhilippeSigaud/Pegged.svg?branch=master)](https://travis-ci.com/PhilippeSigaud/Pegged)

```
[![Build Status](https://travis-ci.com/PhilippeSigaud/Pegged.svg?branch=master)](https://travis-ci.com/PhilippeSigaud/Pegged)
```
and something similar to this for appveyor (you need to copy it from Badges submenu) : 

[![Build status](https://ci.appveyor.com/api/projects/status/hy8ast54god81r6b?svg=true)](https://ci.appveyor.com/project/Zardoz89/pegged)

```
[![Build status](https://ci.appveyor.com/api/projects/status/hy8ast54god81r6b?svg=true)](https://ci.appveyor.com/project/Zardoz89/pegged)
```

**Comment by veelo** [comment]
Thanks. I have contacted Philippe regarding CI access.

**Comment by veelo** [comment]
Done!
