### ISSUE TITLE
How does one do Intellisense using a Pegged grammar?

### ISSUE THREAD

**Issue by enjoysmath** [PhilippeSigaud/Pegged#315]
Everyone wants to know this.  Please show us how that would go.  For example, can we view the grammar as a tree?

I guess we could use the provided PEG example in the example grammars and get a tree, but just wondering if anyone's already solved this problem.

**Comment by veelo** [comment]
You mean you want a language server for a language that is defined by a PEG? You will still have to implement some kind of semantic analyser, a parser alone will be insufficient. A language server needs to build a symbol table, and for that you need to know what rules in the grammar define symbols, and how scope works. 

Or do you want some kind of syntax highlighting for the PEG grammar itself?

**Comment by enjoysmath** [comment]
Yes, the first one.

**Comment by enjoysmath** [comment]
> You mean you want a language server for a language that is defined by a PEG? You will still have to implement some kind of semantic analyser, a parser alone will be insufficient. A language server needs to build a symbol table, and for that you need to know what rules in the grammar define symbols, and how scope works.
> 
> Or do you want some kind of syntax highlighting for the PEG grammar itself?

@veelo do  you know of a good article on how to do that using a symbol table as you've mentioned?
