### ISSUE TITLE
Undocumented features of Pegged

### ISSUE THREAD

**Issue by ahmetsait** [PhilippeSigaud/Pegged#331]
I would like to ask this here to hopefully collect and maybe document these in the wiki if I have the time to experiment with them:

**What are undocumented features of Pegged?**

**Comment by veelo** [comment]
The only thing I am aware of is support for dynamic grammars. https://github.com/PhilippeSigaud/Pegged/tree/master/pegged/dynamic

As far as I know, it is was an experiment that was never finished, and Pegged's implementation would be cleaner if it was just removed.

Do you know of any other holes in the wiki? I am not aware of any.

**Comment by ahmetsait** [comment]
Fair enough. I had a vague memory of pegged having undocumented features while reading through issues past few months.
