### ISSUE TITLE
GrammarTester enhancment proposal

### ISSUE THREAD

**Issue by ricardaxel** [PhilippeSigaud/Pegged#337]
Hello, 

The GrammarTester is very usefull to validate grammars, but it sometimes leads to very long tests.

For example it is quite complicated to test [C grammar](https://github.com/PhilippeSigaud/Pegged/blob/master/examples/c/src/pegged/examples/c.d) , since a single `a = 1` expression is represented as shown below, which is pretty long. 

```
Expression->AssignmentExpression->                                                                                                
{                                                                                                                                                                 
    UnaryExpression->PostfixExpression->PrimaryExpression->Identifier
    AssignmentOperator
    AssignmentExpression->ConditionalExpression->LogicalORExpression->LogicalANDExpression->
        InclusiveORExpression->ExclusiveORExpression->ANDExpression->EqualityExpression->
        RelationalExpression->ShiftExpression->AdditiveExpression->MultiplicativeExpression->
        UnaryExpression->PostfixExpression->PrimaryExpression->IntegerLiteral 
}    
```

Would you be ok to extend testing grammar to shorten some tests, by adding a `{...}` directive that would skip some parts of the tests.

This would give something like this : 

```
tester.assertSimilar(`a = 3`, ` Expression->AssignmentExpression->{...}`); // OK

// Also OK
tester.assertSimilar(`a = 3`, ` 
    Expression->AssignmentExpression->
   {
        UnaryExpression->{...}
        AssignmentOperator
        AssignmentExpression->{...}
    }`); 
```

If you are ok with this proposal, I could make a PR soon

**Comment by veelo** [comment]
I must confess that I have never used GrammarTester, and don't know how it works. The wiki warns that the design may change in the future, so I don't think there is a problem changing it. If I understand you correctly, your proposal would be backwards compatible anyways, right?

Sounds like a good idea, and I look forward to your PR. After it is merged, I kindly request that you extend the existing wiki page to document your changes. And if you could, it would be nice have the CI test the grammar tester, to make sure nothing breaks in the future.

**Comment by ricardaxel** [comment]
> If I understand you correctly, your proposal would be backwards compatible anyways, right?

I confirm. This is just an extension.

> And if you could, it would be nice have the CI test the grammar tester, to make sure nothing breaks in the future.

I also fixed C example since it didn't build anymore, and add test for it using GrammarTester. You can check usage of it [here](https://github.com/PhilippeSigaud/Pegged/pull/338/files#diff-ac72824e4acb05aa02c050e3b24da66f32204e6a8df0a8dbe1607705152c43c3R487)

**Comment by veelo** [comment]
Could you please extend https://github.com/PhilippeSigaud/Pegged/wiki/Grammar-Testing with your contribution?

**Comment by ricardaxel** [comment]
Done, I let you check if it's all good

**Comment by veelo** [comment]
Looks great, thanks.
