### ISSUE TITLE
Wishlist: debug output for grammar parsing

### ISSUE THREAD

**Issue by yoe** [PhilippeSigaud/Pegged#34]
Hi,

I'm trying to parse a file that has standard Unix-style '#-to-EOL' comments; but it's not working, and I believe at this point it's a bug in Pegged (though I'm not 100% sure).

This is my grammar:

---

ENI:
Grammar                 <- Statement (EOL Statement)\* EOL? EOI
Statement               <- ( AutoStatement / HotplugStatement / EmptyLine / Comment )
Comment                 <: '#'
EmptyLine               <: S*
AutoStatement           <- 'auto' S ^Identifier
HotplugStatement        <- 'allow-hotplug' S ^Identifier
## S                       <: ' ' / '\t'

When I give that the following file:

---

auto lo
# 
## allow-hotplug eth0

(i.e., the first line is empty, the third line starts with #)

then it won't parse correctly:

Parse output: failure
named captures: []
position: [index: 0, line: 0, col: 0]
ENI.Grammar failure at pos [index: 9, line: 2, col: 0]
  Pegged.EOI failure at pos [index: 9, line: 2, col: 0]

When taking out the #, it works.

Maybe I'm doing something wrong, but I believe this should just work ,no?

**Comment by veelo** [comment]
> This was made much easier after I changed the code (with a Q&D perl script) so it would write a "matched foo" or "failed to match foo", followed by the complete parse tree, to stdout every time a match or fail would occur. This generates a huge amount of data, but allows you to trace the parser as it's running.
> 
> Perhaps this might be an interesting feature to have in Pegged itself?

This is now implemented, see https://github.com/PhilippeSigaud/Pegged/wiki/Grammar-Debugging.
